version: 2

models:
  - name: raw_houses
    tests:
      - dbt_expectations.expect_table_row_count_to_equal:
          value: 1460
    columns:
      - name: id
        tests:
          - unique
          - not_null
